packages:
  - packages/*
  - packages/start/*

minimumReleaseAge: 10080

allowBuilds:
  esbuild: false
  git-hook-pure: false
  nx: false
  postinstall-postinstall: true

catalogs:
  peerDeps:
    '@types/react': ^16.8.0 || ^16.9.0 || ^18.0.0 || ^19.0.0
    '@types/react-dom': ^16.8.0 || ^16.9.0 || ^18.0.0 || ^19.0.0
    react: ^16.8.0 || ^16.9.0 || ^18.0.0 || ^19.0.0
    react-dom: ^16.8.0 || ^16.9.0 || ^18.0.0 || ^19.0.0
